name: "WhyDidItFail"
description: "Turn GitHub Actions failures into clear root-cause explanations + fixes"
author: "whydiditfail"
branding:
  icon: "image"
  color: "blue"
inputs:
  github_token:
    description: "GitHub token for authentication (defaults to secrets.GITHUB_TOKEN)"
    required: false
    default: ${{ github.token }}
  service_url:
    description: "Base URL of the explanation service (uses hosted service by default)"
    required: false
    default: "https://4tt0zovbna.execute-api.us-east-1.amazonaws.com"
  mode:
    description: "Output mode: 'summary' (job summary) or 'comment' (PR comment)"
    required: false
    default: "summary"
  max_log_kb:
    description: "Maximum log size in KB to send to service"
    required: false
    default: "400"
  redact:
    description: "Redact common secrets from logs before analysis"
    required: false
    default: "true"
  suggest_fixes:
    description: "Post inline fix suggestions as PR review comments or commit comments"
    required: false
    default: "true"
  cleanup_old_comments:
    description: "Clean up old WhyDidItFail comments from previous runs"
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
